---
- name: Pull Docker Image of calculator from Docker Hub
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "chokshi/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Stop all running containers
      shell: docker ps -q | xargs --no-run-if-empty docker stop
      ignore_errors: true

    - name: Remove all stopped containers
      shell: docker ps -a -q | xargs --no-run-if-empty docker rm
      ignore_errors: true

    - name: Run calculator container
      shell: docker run -it -d --name calculator chokshi/calculator